### ISSUE TITLE
TRELLO - Structure

### ISSUE THREAD

**Issue by cpuel** [TeisseireC/PPE_FREDI#1]
Rajouter un bloc "Actvités transverses" afin de suivre :
- La gestion des sources (Github)
- La gestion de la documentation (Google Drive)
- La gestion de la planification (GANTT)

**Comment by TeisseireC** [comment]
Nous avons pris en considération cette issue, les "Activités transverses" ont été rajoutées.

**Comment by cpuel** [comment]
Le bloc "Activités transverses" est bien rajouté. Néanmoins, les items qui y figurent (Github, GoogleDrive, Gantt) doivent être à l'état "En cours", car vous devez régulièrement les mettre à jour.
