### ISSUE TITLE
Installation SQL

### ISSUE THREAD

**Issue by jframiara** [TeisseireC/PPE_FREDI#6]
Pour installer l'application, la doc (README.doc) indique qu'il faut exécuter 12 scripts SQL.
C'est long et pas très pratique.
Il faudrait simplifier en 1 ou 2 scripts SQL. Un programme PHP serait idéal ;-)

**Comment by TeisseireC** [comment]
Bonjour, pour le moment nous réduisons l'installation en 2 scripts ( création de la base et insertion des données ), nous gardons en tête la solution du programme en PHP.
